name: Deploy Website
run-name: ${{ github.actor }} is deploying rubengilbert.com.
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0
      - name: Install sshpass
        run: sudo apt install -y sshpass
      - name: Add SSH Key
        uses: shimataro/ssh-key-action@v2.5.0
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: 'placeholder-to-avoid-errors'
      - name: Add Known Host
        run: ssh-keyscan -H ${{ secrets.DEPLOY_SERVER }} >> ~/.ssh/known_hosts
      - name: Deploy to Server
        run: sshpass -p ${{ secrets.DEPLOY_PASSWORD }} rsync -aP . ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_SERVER }}:${{ secrets.DEPLOY_PATH }} --port=${{ secrets.DEPLOY_PORT }} --exclude=.git --exclude=.github --exclude=.gitignore --exclude=.vscode --exclude=LICENSE --exclude=README*
