name: Deploy Website
run-name: ${{ github.actor }} is deploying rubengilbert.com.
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0
      - name: Install sshpass
        run: apt install sshpass -y
      - name: Add SSH Key
        uses: shimataro/ssh-key-action@v2.5.0
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: 'placeholder-to-avoid-errors'
      - name: Add Known Host
        run: ssh-keyscan -H ${{ secrets.DEPLOY_SERVER }} >> ~/.ssh/known_hosts
